services:
  redis:
    restart: always
    image: redis:alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data
    logging:
      options:
        max-size: 10m

  app:
    restart: always
    depends_on:
      - redis
    build: .
    #image: pyfedicross
    networks:
      - internal_network
    volumes:
      - ./data:/data
    logging:
      options:
        max-size: 10m

  proxy:
    image: nginx
    depends_on:
      - app
    volumes:
      - type: bind
        source: app.template
        target: /etc/nginx/conf.d/app.conf
      - ./data/static:/static
      #- ./data/media:/media
    ports:
     - "80:80"
    networks:
      - external_network
      - internal_network

networks:
  external_network:
  internal_network:
    internal: true