# Generated by Django 5.0 on 2024-02-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fediverseapp',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret'),
        ),
    ]
