# Generated by Django 5.2 on 2025-04-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fediverseapp_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fediverseapp'),
        ),
    ]
